osx_image: xcode7.2
language: objective-c
notifications:
  email:
    miro.kuratczyk@gmail.com
node_js:
- 4
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - brew update
  #- brew install xctool
install:
  - npm install
  - npm install -g react-native-cli
  - npm install tcomb-form-native
  - npm install base-64
  - react-native upgrade
script:
  - react-native run-ios

